### ISSUE TITLE
Live-reload?

### ISSUE THREAD

**Issue by altano** [jnordberg/wintersmith-plugin#1]
Hey there,

I tried to follow the template in raw JS and made a plug-in for both Less compilation and autoprefixing: https://www.npmjs.com/package/wintersmith-autoprefixer-less/

BUT, live-reload isn't working with my plug-in.  The docs on plugins is extremely sparse and I'd rather not have to debug wintersmith itself.  Any ideas what I'm doing wrong or is this template busted in some way?

**Comment by jnordberg** [comment]
Hey, can you elaborate on not working? :)

**Comment by altano** [comment]
I run `wintersmith preview` and then edit a less file and it doesn't rebuild the change, even if I refresh the browser, until I re-run `wintersmith preview` again.

I guess it's not a live-reload issue and it's more of just a rebuilding issue.

**Comment by altano** [comment]
If I created an example repository that reproduces the error, would you have time to take a peek?  No pressure if not.
